<a href="https://colab.research.google.com/github/Ranabirju15/CADD/blob/main/One_Hot_Encoding_Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# List of amino acids
amino_acids = 'ACDEFGHIKLMNPQRSTVWY'

# Create a mapping from amino acid to index
amino_acid_to_index = {aa: i for i, aa in enumerate(amino_acids)}

def one_hot_encode_sequence(sequence):
    # Initialize one-hot encoding matrix
    one_hot_matrix = np.zeros((len(sequence), len(amino_acids)))
    for i, aa in enumerate(sequence):
        if aa in amino_acid_to_index:
            one_hot_matrix[i, amino_acid_to_index[aa]] = 1
    return one_hot_matrix

# Example sequence
sequence = 'ACD'
one_hot_matrix = one_hot_encode_sequence(sequence)
print(one_hot_matrix)


[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
